const song = [
"'Toxic' by Britney Spears",
"'Hurt' by Johnny Cash",
"'Mad World' by Tears for Fears",
"'Arms of an Angel' by Sarah McLachlan",
"'When Somebody Loved Me' by Sarah McLachlan",
"'Billie Jean' by Michael Jackson",
"'The Middle' by Jimmy Eat World",
"'All the Small Things' by Blink-182",
"'Dream On' by Aerosmith",
"'Renegade' by Styx",
"'Maneater' by Hall & Oates",
"'Thank You' by Dido",
"'Everywhere' by Michelle Branch",
// "'Lovesong' by The Cure",
"'River' by Bishop Briggs",
"'Nearly Forgot my Broken Heart' by Chris Cornell",
"'Hook' by Blues Traveler",
"'Dance Monkey' by Tones and I",
"'WAP' by Cardi B feat. Megan Thee Stallion",
"'Can't Help Falling in Love' by Elvis Presley",
"'I'm Yours' by Jason Mraz",
"'1000 Miles' by Vanessa Carlton",
"'Sweet Pea' by Amos Lee",
"'Sweet Dreams' by Eurythmics",
"'Here Comes the Sun' by The Beatles",
"'Ain't No Sunshine' by Bill Withers",
"'Hard to Handle' by The Black Crowes",
"'Tennessee Whiskey' by Chris Stapleton",
"'A Thousand Years' by Christina Perri",
"'The Scientist' by Coldplay",
"'Mr. Jones' by Counting Crows",
"'Babylon' by David Gray",
"'Hold On, We're Going Home' by Drake",
"'Save Tonight' by Eagle-Eye Cherry",
"'Perfect' by Ed Sheeran",
"'Layla' by Eric Clapton & Derek & The Dominos",
"'FourFiveSeconds' by Rihanna, Kanye West, and Paul McCartney",
"'The Joker' by Steve Miller Band",
"'Stand by Me' by Ben E. King",
"'Fast Car' by Tracy Chapman",
"'Drops of Jupiter' by Train",
"'Part Time Lover' by Stevie Wonder", 
"'Sweet Child O' Mine' by Guns N' Roses",
"'Choke' by I DONT KNOW HOW BUT THEY FOUND ME",
"'Heard it Through the Grapevine' by Marvin Gaye",
"'Yesterday' by The Beatles",
"'Let it Be' by The Beatles",
"'Welcome to Paradise' by Green Day",
"'Break my Stride' by Matthew Wilder",
"'Blinding Lights' by The Weeknd",
// "'Adia' by Sarah McLachlan",
"'idontwannabeyouanymore' by Billie Eilish",
"'Karma Police' by Radiohead",
"'Fast Car' by Tracy Chapman",
"'Come to my Window' by Melissa Etheridge",
"'Babylon' by David Gray",
"'Chasing Pavements' by Adele",
"'Where I Stood' by Missy Higgins",
"'Closer' by Ne-Yo",
"'Sign of the Times' by Harry Styles",
"'White Flag' by Bishop Briggs"

];

const style = [
"Girl with a ukulele",
"Shy Ronnie feat. Rihanna",
"feat. DJ Khaled",
"The guy with the guitar at a party, but you actually take song requests",
// "Spoken word/Slam poetry",
"Adele",
"Overenthusiastic theater kid",
"Duet",
"Original Artist",
// "Cher",
"Shakira",
"Pearl Jam",
"Include a vine",
"Drunk girl at karaoke night",
"POV:  You're my crush and I'm singing this song to tell you how I feel",
"David Armand",
"A John Mulaney bit",
"Tom DeLonge",
"The lead singer of the A Capella group who just riffs constantly to impress everyone",
"Can't tell which octave is best for this song and jumps back and forth to figure it out",
"Mariah Carey - NYE 2016",
"You're hooking up with your accompanist and doing a bad job of hiding it",
"You and your accompanist broke up last night, but the show must go on",
"Jammin' out in the car",
"Singing in the shower",
"Lullaby",
"Postmodern Jukebox",
"A parody about the subject of your choice",
"Sing it regular, but while playing the hardest level of a game",
"Serenade one of the cats",
"I walk into my roommate's room and sing it while he's trying to sleep",
"Use household objects for the percussion",
"Yourself"
];